### ISSUE TITLE
Freeze version for certain gems for autoupdate

### ISSUE THREAD

**Issue by bdewater** [gemnasium/toolbelt#17]
I know updating some gems will break tests (Rails 4.1 for example, because we're running 4.0 with https://github.com/rails/activeresource/pull/80) so I would like the ability to keep those gem versions frozen during an autoupdate run. That way Gemnasium can still suggest upgrades while we do the work to get the frozen gems updated :)

**Comment by gravis** [comment]
Hi, thanks for the suggestion, and sorry for the long delay. This is an important feedback, and we will take your comment into consideration, as it was requested by other users too.
I'm leaving this issue open until the release including this change is deployed.

**Comment by gravis** [comment]
Hi, while this feature is not ready yet, the new algorithm deployed today should greatly improve results, and avoid testing big steps like rails major versions.

**Comment by fcat** [comment]
@bdewater The new auto-update algorithm won't upgrade a dependency. So this is a true *update* unlike the previous implementation of the feature. That means you can set the requirement to something like "~> 4.0.13" if you don't want Rails 4.1 or later to be installed.

The legacy auto-update algorithm is still operational for backward compatibility but Toolbelt uses the new one starting from version 0.2.6.
