### ISSUE TITLE
Server returned non-200 status: 500 Internal Server Error

### ISSUE THREAD

**Issue by rochdev** [gemnasium/toolbelt#20]
All non-idempotent commands return the following error: `Server returned non-200 status: 500 Internal Server Error`

For example, I am able to login, list and show projects, list dependencies and dependency files, but when I try to make any changes I always get the same error. I tried to send requests directly to the API using an HTTP client and get the same result.

**Comment by bdewater** [comment]
I've had similar errors and contacted Gemnasium support, who looked at my account/projects and figured out what went wrong. Turns out that in my case the vendored gems' Gemfile and Gemfile.lock were uploaded, and one of our private gems had an unresolved git merge conflict in there. Only pushing the Gemfile and Gemfile.lock of the Rails app did the trick:
`gemnasium df p --files=Gemfile.lock,Gemfile`

If that doesn't work you might have better luck [contacting support](http://support.gemnasium.com/knowledgebase/topics/47707-faq).

**Comment by rochdev** [comment]
Unfortunately there are no conflicts in the JS app so that doesn't seem to be the issue. Thank you anyway for your help!

**Comment by gravis** [comment]
We have published a [new version](https://github.com/gemnasium/toolbelt/releases/tag/0.2.6) of the toolbelt, and the auto-update endpoint. Could you give it a try please?
Thanks

**Comment by rochdev** [comment]
Ok I am now able to do updates to projects both with the API and with toolbelt.

However, when trying to push dependency files using `gemnasium dependency_files push -f bower.json` I receive the error `Sending files to Gemnasium: 500 Internal Server Error: invalid character 'S' looking for beginning of value`

**Comment by gravis** [comment]
Could you post the content of your bower.json file please? It would help to debug that.
Thanks

**Comment by rochdev** [comment]
```json
{
  "name": "angular-check-all",
  "version": "0.0.0",
  "description": "AngularJS directive to control a group of checkboxes",
  "authors": [
    "Roch Devost"
  ],
  "keywords": [
    "angular",
    "angularjs",
    "angular.js",
    "check",
    "checkbox",
    "check-all",
    "checklist",
    "checklist-model",
    "select",
    "select-all"
  ],
  "license": "MIT",
  "private": true,
  "main": "angular-check-all.js",
  "ignore": [
    "**/.*",
    "node_modules",
    "bower_components",
    "test",
    "example",
    "package.json",
    "karma.conf.js"
  ],
  "dependencies": {
    "angular": "~1.2.0"
  },
  "devDependencies": {
    "angular-mocks": "~1.2.0",
    "checklist-model": "~0.1.3"
  }
}
```

**Comment by gravis** [comment]
Thanks!
We have found the issue, and it's now fixed. It wasn't related to your file actually, but an invalid http header. Please feel free to reopen if you have other issues.
