### ISSUE TITLE
Incorrect help on install

### ISSUE THREAD

**Issue by thbar** [gemnasium/toolbelt#21]
After installing with brew I got:

```
If you already have a project on Gemnasium, you'll need to run
  gemnasium projects configure
```

But this command does not seem to exist:

```
$ gemnasium projects configure
No help topic for 'configure'
```

**Comment by gravis** [comment]
Fixed in https://github.com/gemnasium/homebrew-gemnasium/commit/9484b350997adde5053777e010e5f33c2868d9d1
thanks for reporting.
