### ISSUE TITLE
Autoupdate fails when HEAD is detached

### ISSUE THREAD

**Issue by KazW** [gemnasium/toolbelt#23]
As per my findings in #16, the autoupdate command fails when a specific commit has been checked out and the HEAD is detached. This affects any CI server that checks out a specific commit, such as CodeShip.

The gemnasium command will return the following error:
`Server returned non-200 status: 404 Not Found`

Temporary work around (build setup):
```
# Gemnasium Setup
cd $HOME
wget https://github.com/gemnasium/toolbelt/releases/download/${GEMNASIUM_VERSION}/gemnasium_${GEMNASIUM_VERSION}_linux_amd64.tar.gz
tar xf gemnasium_${GEMNASIUM_VERSION}_linux_amd64.tar.gz
cp gemnasium_${GEMNASIUM_VERSION}_linux_amd64/gemnasium bin/gemnasium
rm -rf gemnasium_${GEMNASIUM_VERSION}_linux_amd64 gemnasium_${GEMNASIUM_VERSION}_linux_amd64.tar.gz
# Project setup
cd $HOME/clone
git checkout "$CI_BRANCH"
git reset --hard $CI_COMMIT_ID
git clean -f
rvm use `cat .ruby-version` --install
bin/bundle install
bin/rake db:reset
```

This will move the HEAD back to where it should be for the build, but keep it on the branch. While this works for the master branch, other branches fail.

**Comment by gravis** [comment]
Thanks, this is very useful information, as we couldn't reproduce this kind of error. Now we'll be able to fix it as soon as possible.

**Comment by andynu** [comment]
This (or a similar) issue also affects gitlab-ci.

Using gemnasium 3.2.1

    $ bundle exec gemnasium push
    Not on tracked branch ()
    
    ERROR: Build failed with: exit status 1


This is with the project_branch config in config/gemnasium.yml commented out:

    #project_branch: master        # /!\ If you don't use git, remove this line

**Comment by gravis** [comment]
@andynu the gem is now deprecated, you must use the compiled cli now (https://github.com/gemnasium/toolbelt#how-to-install-it). There's a `REVISION` env var that you can use to tell Gemnasium what is the current revision sha. Thanks

**Comment by andynu** [comment]
Oh! Pardon. Thank you.

**Comment by gravis** [comment]
:)
