### ISSUE TITLE
Can't install generated .deb files on debian/ubuntu

### ISSUE THREAD

**Issue by gravis** [gemnasium/toolbelt#25]
Some users are are hitting this issue while installing the deb files by hand:

```
dpkg: error processing gemnasium-toolbelt_0.2.6_amd64.deb (--install):
 parsing file '/var/lib/dpkg/tmp.ci/control' near line 7 package 'gemnasium-toolbelt':
 `Depends' field, invalid package name `${shlibs': must start with an alphanumeric character
Errors were encountered while processing:
 gemnasium-toolbelt_0.2.6_amd64.deb
```

The deb files on the official repo are valid, because they were build on a debian system, but the packages in releases are compiled with [goxc](https://github.com/laher/goxc), which doesn't expand the `Depends: ${shlibs:Depends}, ${misc:Depends}` macro. 

We are currently looking for a solution.

**Comment by clifff** [comment]
I was just trying to install the `0.2.7` release deb file in Ubuntu and ran into this. Will try the package route if there isn't a work around.

**Comment by gravis** [comment]
The .deb files are also available on apt.gemnasium.com (see README), and don't have this issue.
