### ISSUE TITLE
Configurable autoupdate max duration?

### ISSUE THREAD

**Issue by ajb** [gemnasium/toolbelt#33]
I'm running `gemnasium autoupdate` on CI every night, so I don't particularly care if it takes 5 minutes or 5 hours. However, it looks like the max duration is hard-coded. Would you consider making this a configuration option?

**Comment by gravis** [comment]
Yes, it will be a configurable option in the next version. Until then, we have release a patch version, with no time limit. CI servers have everything to handle that already.
You can download the new versions here: https://github.com/gemnasium/toolbelt/releases/tag/0.2.7
Debian packages will be released later on the official apt source.
