### ISSUE TITLE
There is no runtime dependency.

### ISSUE THREAD

**Issue by deXterbed** [gemnasium/toolbelt#35]
Is there a reason i am seeing this message in my Project's Dashboard even after i have successfully pushed the files(Gemfile & Gemfile.lock) over to the server? I can see the uploaded files on the website

**Comment by fcat** [comment]
The problem originates from Gemnasium.com itself so I turned this GitHub issue into a ticket on http://support.gemnasium.com/

**Comment by deXterbed** [comment]
thanks @fcat
