### ISSUE TITLE
`dependencies list` should return consistent content for same API token and Gemfile.lock

### ISSUE THREAD

**Issue by utako** [gemnasium/toolbelt#36]
We have a job that polls gemnasium using the CLI to get `dependencies list` every hour. 

Sometimes, the response has the full list of our gems with their color coded statuses, but other times, we just get:

```
+--------------+--------------+--------+--------+------------+ | DEPENDENCIES | REQUIREMENTS | LOCKED | STATUS | ADVISORIES | +--------------+--------------+--------+--------+------------+ +--------------+--------------+--------+--------+------------+
```

The API documentation states that there's no rate limiting. If there's another issue, the CLI should return an appropriate error.

**Comment by gravis** [comment]
Hi Utako,

Thanks for reporting this. Could you maybe send more information to support.gemnasium.com (like the email used on gemnasium, and the id of the project)?
I'd like to investigate that.

Thanks,
Philippe

**Comment by utako** [comment]
Sure thing.

Thanks,
Utako
