### ISSUE TITLE
Allow setting AUTOUPDATE_MAX_DURATION

### ISSUE THREAD

**Issue by maxnordlund** [gemnasium/toolbelt#38]
Currently, if you want to run the autoupdate for more then an hour, say during the weekend, you need to work around this cli. While the amount of shell script needed isn't that much, it's bound to be error prone if you just want to raise the cut off time.

Instead of having a hardcoded constant, [`AUTOUPDATE_MAX_DURATION`][1], use that as the default and allow it to be specified as an configuration/environmental variable. Seems reasonable?

[1]: https://github.com/gemnasium/toolbelt/blob/e3290596aa9477ea462e640e196d87d8a6c6e9fc/autoupdate/auto_update.go#L25

**Comment by gravis** [comment]
Hi,
Actually, we are removing this limitation, as everyone can handle timeouts on their side.
You can grab the [0.2.7](https://github.com/gemnasium/toolbelt/releases/tag/0.2.7) version in the [releases section](https://github.com/gemnasium/toolbelt/releases/tag/0.2.7).
I will publish deb files on apt.gemnasium.com tomorrow.

Thanks!

**Comment by gravis** [comment]
(apt.gemnasium.com has been updated)
