### ISSUE TITLE
Move to https

### ISSUE THREAD

**Issue by Br3nda** [gemnasium/toolbelt#45]
Instructions for linux are:
```
sudo sh -c 'echo "deb http://apt.gemnasium.com stable main" > /etc/apt/sources.list.d/gemnasium.list'
```

Can we move to using https instead please? For something getting all the sudo and future update powers, this stands out as a bit scary.

**Comment by gravis** [comment]
Hi Brenda,

You're absolutely right, and the Readme has been fixed accordingly.

Thanks for your vigilance, it's really appreciated.
Philippe

**Comment by Br3nda** [comment]
awesome. you might wanna attempt to migrate existing users too.
