### ISSUE TITLE
No way to separate runtime vs development with `dependency_files push`

### ISSUE THREAD

**Issue by miketheman** [gemnasium/toolbelt#47]
We use toolbelt to push to the Gemnasium endpoint for a project, and cannot make a determination between Python runtime and development requirements, as we push multiple requirements.txt files.

If there was a cli flag to add a second `-f` list that would be dev-only, that might solve it.

**Comment by gravis** [comment]
Hi, have your tried to pass both files using the existing -f flag?
ie: `gemnasium dependency_files push -f= requirements.txt,another_file.txt`

What files are you using by the way?
Thanks

**Comment by miketheman** [comment]
Hi @gravis ,

We use this style of command:

    gemnasium dependency_files p --files=requirements/requirements-base.txt,requirements/requirements-test.txt

There's nothing in them that makes a distinction of development/test dependencies.

**Comment by gravis** [comment]
Ok I see.
Indeed, that's not possible as of today, but we will fix this (probably with the .gemnasium.yaml file).
Thanks for reporting this.
